# Generated by Django 3.2.6 on 2022-11-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_chartmeta_chart_type'),
    ]

    operations = [
        migrations.RunSQL('drop view if exists awc_ah_view'),
            migrations.RunSQL("""create or replace view awc_ah_view as 
                                    select awc_ah.awc_id, awc_ah.user_id as awc_user_id, awc_ah.server_created_on awc_created_on, awc_ah.deactivated_date awc_deactivated_on,
                                    usm.site_id as user_site, awc.village_id as awc_village_id, vlg.grama_panchayat_id as awc_gp_id, gp.block_id as awc_block_id,
                                    blk.district_id as awc_district_id,  dst.state_id as awc_state_id
                                    from application_masters_cc_awc_ah awc_ah
                                    inner join mis_usersitemapping usm on awc_ah.user_id = usm.user_id 
                                    inner join application_masters_awc awc on awc_ah.awc_id = awc.id
                                    inner join application_masters_village vlg on awc.village_id = vlg.id 
                                    inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                    inner join application_masters_block blk on blk.id = gp.block_id 
                                    inner join application_masters_district dst on dst.id = blk.district_id 
                                    inner join application_masters_state st on st.id = dst.state_id 
                                    where awc_ah.status = 1 and usm.status = 1"""),
            migrations.RunSQL('drop view if exists awc_ah_session_view'),
            migrations.RunSQL("""create or replace view awc_ah_session_view as 
                                    select awc_ahs.site_id as user_site, awc_ahs.date_of_session, adl.awc_id, awc.village_id as awc_village_id, vlg.grama_panchayat_id as awc_gp_id, gp.block_id as awc_block_id,
                                    blk.district_id as awc_district_id,  dst.state_id as awc_state_id
                                    from mis_ahsession awc_ahs
                                    inner join application_masters_adolescent adl on awc_ahs.adolescent_name_id = adl.id
                                    inner join application_masters_cc_awc_ah awc_ah on adl.awc_id = awc_ah.awc_id
                                    inner join application_masters_awc awc on adl.awc_id = awc.id
                                    inner join application_masters_village vlg on awc.village_id = vlg.id 
                                    inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                    inner join application_masters_block blk on blk.id = gp.block_id 
                                    inner join application_masters_district dst on dst.id = blk.district_id 
                                    inner join application_masters_state st on st.id = dst.state_id 
                                    where awc_ahs.status = 1 and adl.status = 1
                                    and awc_ahs.date_of_session >= awc_ah.server_created_on and (awc_ah.deactivated_date is null or awc_ahs.date_of_session <= awc_ah.deactivated_date)"""),
            migrations.RunSQL('drop view if exists awc_dl_view'),
            migrations.RunSQL("""create or replace view awc_dl_view as 
                                    select awc_dl.awc_id, awc_dl.user_id as awc_user_id, awc_dl.server_created_on awc_created_on, awc_dl.deactivated_date awc_deactivated_on,
                                    usm.site_id as user_site, awc.village_id as awc_village_id, vlg.grama_panchayat_id as awc_gp_id, gp.block_id as awc_block_id,
                                    blk.district_id as awc_district_id,  dst.state_id as awc_state_id
                                    from application_masters_cc_awc_dl awc_dl
                                    inner join mis_usersitemapping usm on awc_dl.user_id = usm.user_id 
                                    inner join application_masters_awc awc on awc_dl.awc_id = awc.id
                                    inner join application_masters_village vlg on awc.village_id = vlg.id 
                                    inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                    inner join application_masters_block blk on blk.id = gp.block_id 
                                    inner join application_masters_district dst on dst.id = blk.district_id 
                                    inner join application_masters_state st on st.id = dst.state_id 
                                    where awc_dl.status = 1 and usm.status = 1"""),
            migrations.RunSQL('drop view if exists awc_dl_session_view'),
            migrations.RunSQL("""create or replace view awc_dl_session_view as 
                                    select awc_dls.site_id as user_site, awc_dls.date_of_session, adl.awc_id, awc.village_id as awc_village_id, vlg.grama_panchayat_id as awc_gp_id, gp.block_id as awc_block_id,
                                    blk.district_id as awc_district_id,  dst.state_id as awc_state_id
                                    from mis_dlsession awc_dls
                                    inner join application_masters_adolescent adl on awc_dls.adolescent_name_id = adl.id
                                    inner join application_masters_cc_awc_dl awc_dl on adl.awc_id = awc_dl.awc_id
                                    inner join application_masters_awc awc on adl.awc_id = awc.id
                                    inner join application_masters_village vlg on awc.village_id = vlg.id 
                                    inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                    inner join application_masters_block blk on blk.id = gp.block_id 
                                    inner join application_masters_district dst on dst.id = blk.district_id 
                                    inner join application_masters_state st on st.id = dst.state_id 
                                    where awc_dls.status = 1 and adl.status = 1
                                    and awc_dls.date_of_session >= awc_dl.server_created_on and (awc_dl.deactivated_date is null or awc_dls.date_of_session <= awc_dl.deactivated_date)"""),
            migrations.RunSQL('drop view if exists user_site_info_view'),
            migrations.RunSQL("""create or replace view user_site_info_view as 
                                    select aug.user_id, aug.group_id, ag.name as group_name, usm.status as user_site_status , usm.site_id as user_site, usm.server_created_on as created_on,
                                    (case when usm.status = 1 then null else usm.server_modified_on end) as deactivated_date
                                    from auth_user_groups aug 
                                    inner join auth_group ag on ag.id = aug.group_id
                                    inner join mis_usersitemapping usm on aug.user_id = usm.user_id"""),
            migrations.RunSQL('drop view if exists user_task_info_view'),
            migrations.RunSQL("""create or replace view user_task_info_view as 
                                    select user_id, id as task_id, start_date as task_start_date,  end_date as task_end_date, task_status 
                                    from mis_task
                                    where status = 1"""),
            migrations.RunSQL('drop view if exists vocational_training_placement_view'),
            migrations.RunSQL("""create or replace view vocational_training_placement_view as 
                                    select avt.date_of_registration, avt.training_complated, avt.placement_offered, avt.placement_accepted, 
                                    avt.adolescent_name_id, avt.site_id as training_site, avt.type_of_employment, 
                                    ts.id as subject_id, ts.training_subject as subject_name, ad.age_in_completed_years as adolescent_age_yrs, 
                                    ad.gender as adolescent_gender
                                    from mis_adolescentvocationaltraining avt 
                                    inner join application_masters_trainingsubject ts on avt.training_subject_id = ts.id
                                    inner join application_masters_adolescent ad on ad.id = avt.adolescent_name_id
                                    where avt.status = 1 and ts.status = 1 """),                                
            migrations.RunSQL('drop view if exists community_engagement_view'),
            migrations.RunSQL("""create or replace view community_engagement_view as 
                                    select cea.activity_name_id, cea.girls_10_14_year, cea.girls_15_19_year, cea.boys_10_14_year, cea.boys_15_19_year, cea.champions_15_19_year, cea.adult_male, cea.adult_female, cea.teachers, cea.pri_members, cea.services_providers, cea.sms_members, cea.other, cea.site_id as activity_site, cea.village_name_id as village_id,
                                    vlg.name as village_name, vlg.grama_panchayat_id as gp_id, gp.name as gp_name, gp.block_id as block_id, blk.name as block_name, blk.district_id, dst.name as district_name, dst.state_id, st.name as state_name
                                    from mis_communityengagementactivities as cea
                                    inner join application_masters_village vlg on cea.village_name_id = vlg.id 
                                    inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                    inner join application_masters_block blk on blk.id = gp.block_id 
                                    inner join application_masters_district dst on dst.id = blk.district_id 
                                    inner join application_masters_state st on st.id = dst.state_id 
                                    where cea.status = 1"""),                                
            migrations.RunSQL('drop view if exists adolescent_referred_view'),
            migrations.RunSQL("""create or replace view adolescent_referred_view as 
                                    select ad_ref.awc_name_id as awc_id, ad_ref.task_id, ad_ref.site_id as referred_at_site, ad_ref.girls_hwc_referred, ad_ref.girls_hwc_visited, ad_ref.girls_afhc_referred, ad_ref.girls_afhc_visited, ad_ref.girls_dh_referred,ad_ref.girls_dh_visited, ad_ref.boys_hwc_referred,ad_ref.boys_hwc_visited, ad_ref.boys_afhc_referred, ad_ref.boys_afhc_visited, ad_ref.boys_dh_referred, ad_ref.boys_dh_visited, awc.village_id as village_id, vlg.name as village_name, vlg.grama_panchayat_id as gp_id, gp.name as gp_name, gp.block_id as block_id, blk.name as block_name, blk.district_id, dst.name as district_name, dst.state_id, st.name as state_name
                                    from mis_adolescentsreferred ad_ref
                                    inner join application_masters_awc awc on awc.id = ad_ref.awc_name_id
                                    inner join application_masters_village vlg on awc.village_id = vlg.id 
                                    inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                    inner join application_masters_block blk on blk.id = gp.block_id 
                                    inner join application_masters_district dst on dst.id = blk.district_id 
                                    inner join application_masters_state st on st.id = dst.state_id 
                                    where ad_ref.status = 1"""),                                
            migrations.RunSQL('drop view if exists afc_meeting_view'),
            migrations.RunSQL("""create or replace view afc_meeting_view as 
                                    select afc.subject, afc.no_of_sahiya, afc.no_of_aww, afc.pe_girls_10_14_year, afc.pe_girls_15_19_year, afc.pe_boys_10_14_year, afc.pe_boys_15_19_year, afc.task_id, afc.site_id as afc_site, afc.panchayat_name_id as gp_id, gp.name as gp_name, gp.block_id as block_id, blk.name as block_name, blk.district_id, dst.name as district_name, dst.state_id, st.name as state_name
                                    from mis_adolescentfriendlyclub as afc
                                    inner join application_masters_gramapanchayat gp on afc.panchayat_name_id = gp.id 
                                    inner join application_masters_block blk on blk.id = gp.block_id 
                                    inner join application_masters_district dst on dst.id = blk.district_id 
                                    inner join application_masters_state st on st.id = dst.state_id 
                                    where afc.status = 1"""),                                
            migrations.RunSQL('drop view if exists balsansad_meeting_view'),
            migrations.RunSQL("""create or replace view balsansad_meeting_view as 
                                    select bsm.no_of_participants, bsm.task_id, bsm.site_id as balsansad_site, bsm.school_name_id as school_id,
                                    ams.village_id, vlg.name as village_name, vlg.grama_panchayat_id as gp_id, gp.name as gp_name, gp.block_id as block_id, blk.name as block_name, blk.district_id, dst.name as district_name, dst.state_id, st.name as state_name
                                    from mis_balsansadmeeting as bsm
                                    inner join application_masters_school ams on ams.id = bsm.school_name_id
                                    inner join application_masters_village vlg on ams.village_id = vlg.id 
                                    inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                    inner join application_masters_block blk on blk.id = gp.block_id 
                                    inner join application_masters_district dst on dst.id = blk.district_id 
                                    inner join application_masters_state st on st.id = dst.state_id 
                                    where bsm.status = 1"""),                                
            migrations.RunSQL('drop view if exists exposure_adl_champions_view'),
            migrations.RunSQL("""create or replace view exposure_adl_champions_view as 
                                    select chmp.task_id, chmp.site_id as champions_site, chmp.awc_name_id as awc_id, chmp.girls_10_14_year, chmp.girls_15_19_year, chmp.boys_10_14_year, chmp.boys_15_19_year, awc.village_id, vlg.name as village_name, vlg.grama_panchayat_id as gp_id, gp.name as gp_name, gp.block_id as block_id, blk.name as block_name, blk.district_id, dst.name as district_name, dst.state_id, st.name as state_name, chmp.first_inst_visited, chmp.second_inst_visited, chmp.third_inst_visited, chmp.fourth_inst_visited
                                    from mis_champions as chmp
                                    inner join application_masters_awc awc on awc.id = chmp.awc_name_id
                                    inner join application_masters_village vlg on awc.village_id = vlg.id 
                                    inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                    inner join application_masters_block blk on blk.id = gp.block_id 
                                    inner join application_masters_district dst on dst.id = blk.district_id 
                                    inner join application_masters_state st on st.id = dst.state_id 
                                    where chmp.status = 1"""),                                
        ] 

    
