# Generated by Django 3.2.6 on 2022-12-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_views'),
    ]

    operations = [
        migrations.RunSQL('drop view if exists awc_ah_view'),
        migrations.RunSQL("""create or replace view awc_ah_view as 
                                select awc_ah.awc_id, awc_ah.user_id as awc_user_id, awc_ah.server_created_on awc_created_on, awc_ah.deactivated_date awc_deactivated_on,
                                usm.site_id as user_site, awc.village_id as awc_village_id, vlg.grama_panchayat_id as awc_gp_id, gp.block_id as awc_block_id,
                                blk.district_id as awc_district_id,  dst.state_id as awc_state_id
                                from application_masters_cc_awc_ah awc_ah
                                inner join mis_usersitemapping usm on awc_ah.user_id = usm.user_id 
                                inner join application_masters_awc awc on awc_ah.awc_id = awc.id
                                inner join application_masters_village vlg on awc.village_id = vlg.id 
                                inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where awc_ah.status = 1 and usm.status = 1"""),
        migrations.RunSQL('drop view if exists awc_ah_session_view'),
        migrations.RunSQL("""create or replace view awc_ah_session_view as 
                                select awc_ahs.site_id as user_site, mt.user_id as awc_user_id, awc_ahs.date_of_session, adl.name, adl.gender, adl.age_in_completed_years as adolescent_age_yrs, adl.awc_id, awc.village_id as awc_village_id, vlg.grama_panchayat_id as awc_gp_id, gp.block_id as awc_block_id, blk.name as block_name,
                                blk.district_id as awc_district_id,  dst.state_id as awc_state_id
                                from mis_ahsession awc_ahs
                                inner join application_masters_adolescent adl on awc_ahs.adolescent_name_id = adl.id
                                inner join application_masters_awc awc on adl.awc_id = awc.id
                                inner join mis_task mt on mt.id = awc_ahs.task_id
                                inner join application_masters_village vlg on awc.village_id = vlg.id 
                                inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where awc_ahs.status = 1 and adl.status = 1 and mt.status = 1"""),
        migrations.RunSQL('drop view if exists awc_dl_view'),
        migrations.RunSQL("""create or replace view awc_dl_view as 
                                select awc_dl.awc_id, awc_dl.user_id as awc_user_id, awc_dl.server_created_on awc_created_on, awc_dl.deactivated_date awc_deactivated_on,
                                usm.site_id as user_site, awc.village_id as awc_village_id, vlg.grama_panchayat_id as awc_gp_id, gp.block_id as awc_block_id,
                                blk.district_id as awc_district_id,  dst.state_id as awc_state_id
                                from application_masters_cc_awc_dl awc_dl
                                inner join mis_usersitemapping usm on awc_dl.user_id = usm.user_id 
                                inner join application_masters_awc awc on awc_dl.awc_id = awc.id
                                inner join application_masters_village vlg on awc.village_id = vlg.id 
                                inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where awc_dl.status = 1 and usm.status = 1"""),
        migrations.RunSQL('drop view if exists awc_dl_session_view'),
        migrations.RunSQL("""create or replace view awc_dl_session_view as 
                                select awc_dls.site_id as user_site, mt.user_id as awc_user_id, awc_dls.date_of_session, adl.name, adl.gender, adl.age_in_completed_years as adolescent_age_yrs, adl.awc_id, awc.village_id as awc_village_id, vlg.grama_panchayat_id as awc_gp_id, gp.block_id as awc_block_id, blk.name as block_name,
                                blk.district_id as awc_district_id,  dst.state_id as awc_state_id
                                from mis_dlsession awc_dls
                                inner join application_masters_adolescent adl on awc_dls.adolescent_name_id = adl.id
                                --inner join application_masters_cc_awc_dl awc_dl on adl.awc_id = awc_dl.awc_id
                                inner join application_masters_awc awc on adl.awc_id = awc.id
                                inner join mis_task mt on mt.id = awc_dls.task_id
                                inner join application_masters_village vlg on awc.village_id = vlg.id 
                                inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where awc_dls.status = 1 and adl.status = 1 and mt.status = 1"""),
        migrations.RunSQL('drop view if exists user_site_info_view'),
        migrations.RunSQL("""create or replace view user_site_info_view as 
                                select aug.user_id, aug.group_id, ag.name as group_name, usm.status as user_site_status , usm.site_id as user_site, usm.server_created_on as created_on,
                                (case when usm.status = 1 then null else usm.server_modified_on end) as deactivated_date
                                from auth_user_groups aug 
                                inner join auth_group ag on ag.id = aug.group_id
                                inner join mis_usersitemapping usm on aug.user_id = usm.user_id"""),
        migrations.RunSQL('drop view if exists user_task_info_view'),
        migrations.RunSQL("""create or replace view user_task_info_view as 
                                select user_id, id as task_id, start_date as task_start_date,  end_date as task_end_date, task_status 
                                from mis_task
                                where status = 1"""),
        migrations.RunSQL('drop view if exists vocational_training_placement_view'),
        migrations.RunSQL("""create or replace view vocational_training_placement_view as 
                                select avt.date_of_registration, avt.training_complated, avt.placement_offered, avt.placement_accepted, 
                                avt.adolescent_name_id, avt.site_id as training_site, avt.type_of_employment, 
                                ts.id as subject_id, ts.training_subject as subject_name, ad.age_in_completed_years as adolescent_age_yrs, 
                                ad.gender as adolescent_gender, mt.user_id as user_id, ad.awc_id, awc.village_id as awc_village_id, vlg.grama_panchayat_id as awc_gp_id, gp.block_id as awc_block_id, blk.name as block_name,
                                blk.district_id as awc_district_id,  dst.state_id as awc_state_id
                                from mis_adolescentvocationaltraining avt 
                                inner join application_masters_trainingsubject ts on avt.training_subject_id = ts.id
                                inner join application_masters_adolescent ad on ad.id = avt.adolescent_name_id
                                inner join application_masters_awc awc on ad.awc_id = awc.id
                                inner join mis_task mt on mt.id = avt.task_id
                                inner join application_masters_village vlg on awc.village_id = vlg.id 
                                inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where avt.status = 1 and ts.status = 1 """),
        migrations.RunSQL('drop view if exists community_engagement_view'),
        migrations.RunSQL("""create or replace view community_engagement_view as 
                                select cea.activity_name_id, cea.girls_10_14_year, cea.girls_15_19_year, cea.boys_10_14_year, cea.boys_15_19_year, cea.champions_15_19_year, cea.adult_male, cea.adult_female, cea.teachers, cea.pri_members, cea.services_providers, cea.sms_members, cea.other, cea.start_date as activity_date, cea.site_id as activity_site, mt.user_id, cea.village_name_id as village_id,
                                vlg.name as village_name, vlg.grama_panchayat_id as gp_id, gp.name as gp_name, gp.block_id as block_id, blk.name as block_name, blk.district_id, dst.name as district_name, dst.state_id, st.name as state_name
                                from mis_communityengagementactivities as cea
                                inner join mis_task mt on mt.id = cea.task_id
                                inner join application_masters_village vlg on cea.village_name_id = vlg.id 
                                inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where cea.status = 1"""),
        migrations.RunSQL('drop view if exists adolescent_referred_view'),
        migrations.RunSQL("""create or replace view adolescent_referred_view as 
                                select ad_ref.awc_name_id as awc_id, mt.user_id, ad_ref.server_created_on as created_on, ad_ref.task_id, ad_ref.site_id as referred_at_site, ad_ref.girls_hwc_referred, ad_ref.girls_hwc_visited, ad_ref.girls_afhc_referred, ad_ref.girls_afhc_visited, ad_ref.girls_dh_referred,ad_ref.girls_dh_visited, ad_ref.boys_hwc_referred,ad_ref.boys_hwc_visited, ad_ref.boys_afhc_referred, ad_ref.boys_afhc_visited, ad_ref.boys_dh_referred, ad_ref.boys_dh_visited, awc.village_id as village_id, vlg.name as village_name, vlg.grama_panchayat_id as gp_id, gp.name as gp_name, gp.block_id as block_id, blk.name as block_name, blk.district_id, dst.name as district_name, dst.state_id, st.name as state_name
                                from mis_adolescentsreferred ad_ref
                                inner join mis_task mt on mt.id = ad_ref.task_id
                                inner join application_masters_awc awc on awc.id = ad_ref.awc_name_id
                                inner join application_masters_village vlg on awc.village_id = vlg.id 
                                inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where ad_ref.status = 1"""),
        migrations.RunSQL('drop view if exists afc_meeting_view'),
        migrations.RunSQL("""create or replace view afc_meeting_view as 
                                select afc.subject, afc.no_of_sahiya, afc.no_of_aww, afc.pe_girls_10_14_year, afc.pe_girls_15_19_year, afc.pe_boys_10_14_year, afc.pe_boys_15_19_year, afc.task_id, mt.user_id, afc.site_id as afc_site, afc.panchayat_name_id as gp_id, gp.name as gp_name, gp.block_id as block_id, blk.name as block_name, blk.district_id, dst.name as district_name, dst.state_id, st.name as state_name, afc.start_date 
                                from mis_adolescentfriendlyclub as afc
                                inner join mis_task mt on mt.id = afc.task_id
                                inner join application_masters_gramapanchayat gp on afc.panchayat_name_id = gp.id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where afc.status = 1"""),
        migrations.RunSQL('drop view if exists balsansad_meeting_view'),
        migrations.RunSQL("""create or replace view balsansad_meeting_view as 
                                select bsm.no_of_participants, bsm.task_id, bsm.site_id as balsansad_site, bsm.start_date, mt.user_id, bsm.school_name_id as school_id, ams.village_id, vlg.name as village_name, vlg.grama_panchayat_id as gp_id, gp.name as gp_name, gp.block_id as block_id, blk.name as block_name, blk.district_id, dst.name as district_name, dst.state_id, st.name as state_name
                                from mis_balsansadmeeting as bsm
                                inner join mis_task mt on mt.id = bsm.task_id
                                inner join application_masters_school ams on ams.id = bsm.school_name_id
                                inner join application_masters_village vlg on ams.village_id = vlg.id 
                                inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where bsm.status = 1"""),
        migrations.RunSQL('drop view if exists exposure_adl_champions_view'),
        migrations.RunSQL("""create or replace view exposure_adl_champions_view as 
                                select chmp.task_id, chmp.date_of_visit, chmp.site_id as champions_site, mt.user_id, chmp.awc_name_id as awc_id, chmp.girls_10_14_year, chmp.girls_15_19_year, chmp.boys_10_14_year, chmp.boys_15_19_year, awc.village_id, vlg.name as village_name, vlg.grama_panchayat_id as gp_id, gp.name as gp_name, gp.block_id as block_id, blk.name as block_name, blk.district_id, dst.name as district_name, dst.state_id, st.name as state_name, 
                                coalesce(chmp.first_inst_visited,0) as first_inst_visited, coalesce(chmp.second_inst_visited,0) as second_inst_visited, 
                                coalesce(chmp.third_inst_visited,0) as third_inst_visited, coalesce(chmp.fourth_inst_visited,0) as fourth_inst_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 1 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 1 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 1 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 1 then 1 else 0 end)) as chc_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 2 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 2 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 2 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 2 then 1 else 0 end)) as afhc_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 3 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 3 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 3 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 3 then 1 else 0 end)) as hsc_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 4 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 4 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 4 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 4 then 1 else 0 end)) as hwc_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 5 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 5 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 5 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 5 then 1 else 0 end)) as police_station_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 6 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 6 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 6 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 6 then 1 else 0 end)) as post_office_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 7 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 7 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 7 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 7 then 1 else 0 end)) as bank_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 8 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 8 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 8 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 8 then 1 else 0 end)) as pragya_kendra_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 9 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 9 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 9 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 9 then 1 else 0 end)) as panchayat_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 10 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 10 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 10 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 10 then 1 else 0 end)) as employment_exchange_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 11 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 11 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 11 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 11 then 1 else 0 end)) as zoo_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 12 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 12 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 12 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 12 then 1 else 0 end)) as science_park_visited,
                                ((case when coalesce(chmp.first_inst_visited,0) = 13 then 1 else 0 end) + (case when coalesce(chmp.second_inst_visited,0) = 13 then 1 else 0 end) + (case when coalesce(chmp.third_inst_visited,0) = 13 then 1 else 0 end) + (case when coalesce(chmp.fourth_inst_visited,0) = 13 then 1 else 0 end)) as other_visited
                                from mis_champions as chmp
                                inner join mis_task mt on mt.id = chmp.task_id
                                inner join application_masters_awc awc on awc.id = chmp.awc_name_id
                                inner join application_masters_village vlg on awc.village_id = vlg.id 
                                inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where chmp.status = 1"""),
        migrations.RunSQL('drop view if exists ahwd_info_view'),
        migrations.RunSQL("""create or replace view ahwd_info_view as 
                                select ahwd.task_id, ahwd.site_id as ahwd_site, ahwd.date_of_ahwd as date_of_ahwd, mt.user_id,
                                ahwd.participated_10_14_years, ahwd.participated_15_19_years, ahwd.bmi_10_14_years, ahwd.bmi_15_19_years, ahwd.hb_10_14_years, ahwd.hb_15_19_years, ahwd.tt_10_14_years, ahwd.tt_15_19_years, ahwd.counselling_10_14_years, ahwd.counselling_15_19_years, ahwd.referral_10_14_years, ahwd.referral_15_19_years,ahwd.object_id as location_id,
                                ams.village_id, vlg.name as village_name, vlg.grama_panchayat_id as gp_id, gp.name as gp_name, gp.block_id as block_id, blk.name as block_name, blk.district_id, dst.name as district_name, dst.state_id, st.name as state_name
                                from mis_girlsahwd as ahwd
                                inner join mis_task mt on mt.id = ahwd.task_id
                                inner join application_masters_school ams on ams.id = ahwd.object_id and ahwd.content_type_id = 16
                                inner join application_masters_village vlg on ams.village_id = vlg.id 
                                inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where ahwd.status = 1"""),
        migrations.RunSQL('drop view if exists adolescentre_enrolled_view'),
        migrations.RunSQL("""create or replace view adolescentre_enrolled_view as 
                                select mae.task_id, mt.user_id, mae.site_id as enrolled_site,  mae.server_created_on::date as enrolled_date,
                                mae.which_class_enrolled, mae.adolescent_name_id, adl.age_in_completed_years as adolescent_age_yrs, 
                                adl.gender as adolescent_gender, adl.awc_id, awc.village_id as awc_village_id, vlg.grama_panchayat_id as awc_gp_id, gp.block_id as awc_block_id, blk.name as block_name, blk.district_id as awc_district_id,  dst.state_id as awc_state_id
                                from mis_adolescentre_enrolled mae 
                                inner join mis_task mt on mae.task_id = mt.id
                                inner join application_masters_adolescent adl on adl.id = mae.adolescent_name_id
                                inner join application_masters_cc_awc_ah awc_ah on adl.awc_id = awc_ah.awc_id
                                inner join user_site_info_view usiv on usiv.user_id = awc_ah.user_id and mae.server_created_on >= usiv.created_on and (usiv.deactivated_date is null or mae.server_created_on <= usiv.deactivated_date)
                                inner join application_masters_awc awc on adl.awc_id = awc.id
                                inner join application_masters_village vlg on awc.village_id = vlg.id 
                                inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where mae.status = 1 and adl.status = 1 
                                and mae.server_created_on::date >= usiv.created_on::date and (usiv.deactivated_date is null or mae.server_created_on::date <= usiv.deactivated_date::date)"""),
        migrations.RunSQL('drop view if exists awc_adolescent_enrolled_view'),
        migrations.RunSQL("""create or replace view awc_adolescent_enrolled_view as 
                                select  adl.name, adl.gender, adl.age_in_completed_years as adolescent_age_yrs, adl.awc_id, awc_ah.user_id as awc_user_id, awc.village_id as awc_village_id, vlg.grama_panchayat_id as awc_gp_id, gp.block_id as awc_block_id, blk.name as block_name,
                                blk.district_id as awc_district_id,  dst.state_id as awc_state_id, usm.site_id as user_site, adl.server_created_on as created_on
                                from application_masters_adolescent adl
                                inner join application_masters_cc_awc_ah awc_ah on adl.awc_id = awc_ah.awc_id
                                inner join mis_usersitemapping usm on usm.user_id = awc_ah.user_id
                                inner join application_masters_awc awc on adl.awc_id = awc.id
                                inner join application_masters_village vlg on awc.village_id = vlg.id 
                                inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                inner join application_masters_block blk on blk.id = gp.block_id 
                                inner join application_masters_district dst on dst.id = blk.district_id 
                                inner join application_masters_state st on st.id = dst.state_id 
                                where awc_ah.status = 1 and adl.status = 1 and usm.status = 1
                                and awc_ah.server_created_on >= usm.server_created_on and (usm.status = 1 or awc_ah.deactivated_date <= usm.server_modified_on)"""),
    ] 
