# Generated by Django 3.2.6 on 2023-01-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_update_views'),
    ]

    operations = [
            migrations.RunSQL('drop view if exists awc_adolescent_enrolled_view'),
            migrations.RunSQL("""create or replace view awc_adolescent_enrolled_view as 
                                    select  adl.name, adl.gender, adl.age_in_completed_years as adolescent_age_yrs, adl.awc_id, awc_ah.user_id as awc_user_id, awc.village_id as awc_village_id, vlg.grama_panchayat_id as awc_gp_id, gp.block_id as awc_block_id, blk.name as block_name,
                                    blk.district_id as awc_district_id,  dst.state_id as awc_state_id, usm.site_id as user_site, adl.server_created_on as created_on,
                                    awc_ah.deactivated_date as cc_awc_ah_deactivated_date, usm.status as usm_status, awc_ah.status as cc_awc_ah_status
                                    from application_masters_adolescent adl
                                    inner join application_masters_cc_awc_ah awc_ah on adl.awc_id = awc_ah.awc_id
                                    inner join mis_usersitemapping usm on usm.user_id = awc_ah.user_id
                                    inner join application_masters_awc awc on adl.awc_id = awc.id
                                    inner join application_masters_village vlg on awc.village_id = vlg.id 
                                    inner join application_masters_gramapanchayat gp on gp.id = vlg.grama_panchayat_id 
                                    inner join application_masters_block blk on blk.id = gp.block_id 
                                    inner join application_masters_district dst on dst.id = blk.district_id 
                                    inner join application_masters_state st on st.id = dst.state_id 
                                    where adl.status = 1"""),
        ]
