# Generated by Django 3.2.4 on 2023-02-27 07:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_ah_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('page_slug', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters are allowed.')])),
                ('report_slug', models.CharField(blank=True, max_length=500, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z-]*$', 'Only alphanumeric characters are allowed.')])),
                ('report_title', models.CharField(blank=True, max_length=500, null=True)),
                ('report_header', models.JSONField(blank=True, help_text='report headers in json format', null=True)),
                ('report_query', models.JSONField(blank=True, help_text='sql query and related filter details as json - with keys sqlquery, filters and etc', null=True)),
                ('display_order', models.IntegerField(blank=True, help_text='order in which the charts have to be displayed', null=True)),
                ('filter_info', models.JSONField(blank=True, help_text='report filters meta data in json format', null=True)),
                ('sort_info', models.JSONField(blank=True, help_text='report sort meta data in json format', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createddashboard_reportmeta_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifieddashboard_reportmeta_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Report Meta',
                'ordering': ['display_order'],
            },
        ),
    ]
