# Generated by Django 3.2.4 on 2023-02-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_reportmeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmeta',
            name='page_slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reportmeta',
            name='report_slug',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
