# Generated by Django 3.2.4 on 2023-03-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20230227_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmeta',
            name='site_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
