# Generated by Django 3.2.4 on 2023-03-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_reportmeta_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmeta',
            name='report_slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
