# Generated by Django 4.2.2 on 2023-06-28 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_chartmeta_created_by_and_more'),
    ]

    operations = [
        migrations.RunSQL('drop view if exists awc_ah_session_view'),
        migrations.RunSQL("""create or replace view awc_ah_session_view as 
SELECT awc_ahs.site_id AS user_site,
    awc_ahs.adolescent_name_id,
    mt.user_id AS awc_user_id,
    awc_ahs.date_of_session,
    adl.name,
    adl.gender,
    adl.age_in_completed_years AS adolescent_age_yrs,
    adl.awc_id,
    awc.village_id AS awc_village_id,
    vlg.grama_panchayat_id AS awc_gp_id,
    gp.block_id AS awc_block_id,
    blk.name AS block_name,
    blk.district_id AS awc_district_id,
    dst.state_id AS awc_state_id
   FROM mis_ahsession awc_ahs
     JOIN application_masters_adolescent adl ON awc_ahs.adolescent_name_id = adl.id
     JOIN application_masters_awc awc ON adl.awc_id = awc.id
     JOIN mis_task mt ON mt.id = awc_ahs.task_id
     JOIN application_masters_village vlg ON awc.village_id = vlg.id
     JOIN application_masters_gramapanchayat gp ON gp.id = vlg.grama_panchayat_id
     JOIN application_masters_block blk ON blk.id = gp.block_id
     JOIN application_masters_district dst ON dst.id = blk.district_id
     JOIN application_masters_state st ON st.id = dst.state_id
  WHERE awc_ahs.status = 1 AND adl.status = 1 AND mt.status = 1"""),
        migrations.RunSQL('drop view if exists awc_adolescent_enrolled_view'),
        migrations.RunSQL("""create or replace view awc_adolescent_enrolled_view as 
 SELECT adl.name,
    adl.gender,
    adl.age_in_completed_years AS adolescent_age_yrs,
    adl.awc_id,
    awc.village_id AS awc_village_id,
    vlg.grama_panchayat_id AS awc_gp_id,
    gp.block_id AS awc_block_id,
    blk.name AS block_name,
    blk.district_id AS awc_district_id,
    dst.state_id AS awc_state_id,
    adl.site AS user_site,
    adl.server_created_on AS created_on
   FROM application_masters_adolescent adl
     JOIN application_masters_awc awc ON adl.awc_id = awc.id
     JOIN application_masters_village vlg ON awc.village_id = vlg.id
     JOIN application_masters_gramapanchayat gp ON gp.id = vlg.grama_panchayat_id
     JOIN application_masters_block blk ON blk.id = gp.block_id
     JOIN application_masters_district dst ON dst.id = blk.district_id
     JOIN application_masters_state st ON st.id = dst.state_id
  WHERE adl.status = 1"""),
    ]
