# Generated by Django 4.2.2 on 2023-09-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_health_session_attended'),
    ]

    operations = [
        migrations.RunSQL('drop view if exists awc_adolescent_enrolled_view'),
        migrations.RunSQL("""create or replace view awc_adolescent_enrolled_view as 
 SELECT adl.name,
    adl.gender,
    adl.age_in_completed_years AS adolescent_age_yrs,
    adl.awc_id,
    awc.village_id AS awc_village_id,
    vlg.grama_panchayat_id AS awc_gp_id,
    gp.block_id AS awc_block_id,
    blk.name AS block_name,
    blk.district_id AS awc_district_id,
    dst.state_id AS awc_state_id,
    adl.site AS user_site,
    adl.server_created_on AS created_on
   FROM application_masters_adolescent adl
     JOIN application_masters_awc awc ON adl.awc_id = awc.id
     JOIN mis_usersitemapping usm on usm.site_id=adl.site 
     JOIN application_masters_cc_awc_ah  cal on adl.awc_id=cal.awc_id and usm.user_id=cal.user_id and cal.status=1
     JOIN auth_user au on cal.user_id=au.id
     JOIN application_masters_village vlg ON awc.village_id = vlg.id
     JOIN application_masters_gramapanchayat gp ON gp.id = vlg.grama_panchayat_id
     JOIN application_masters_block blk ON blk.id = gp.block_id
     JOIN application_masters_district dst ON dst.id = blk.district_id
     JOIN application_masters_state st ON st.id = dst.state_id
  WHERE adl.status = 1"""),
    ]
