"""
Django settings for C3_WEB project.



Generated by 'django-admin startproject' using Django 3.2.4.



For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/



For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""



from pathlib import Path
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$33l6d@3o_iu0kslzwbqz!_7z+gw=2i0_89!kti(i03us9ml$1'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False 




# Application definition



INSTALLED_APPS = [
    'application_masters',
    'dashboard',
    'mis',
    'import_export',
    'silk',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'silk.middleware.SilkyMiddleware',
]



ROOT_URLCONF = 'C3_WEB.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates/', ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'C3_WEB.wsgi.application'




# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases



# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
#        'NAME': 'c3_mis_devdb_03dec2022',
        'NAME': 'c3_nov13',
        'USER': 'postgres',
        'PASSWORD': 'Loga@589',
        'HOST': 'localhost',
        'PORT': '',
    }
}




# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators



AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/



LANGUAGE_CODE = 'en-us'



#TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Kolkata'



USE_I18N = True



USE_L10N = True



USE_TZ = True



SITE_ID = 2



# ACCOUNT_DEFAULT_HTTP_PROTOCOL='https'



ALLOWED_HOSTS = ['*']




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/



STATIC_URL = '/static/'



# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




MEDIA_URL = '/media/'
MEDIA_DIR = (BASE_DIR / 'media')



# Added for after debug is false static files are not detected



if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')




MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
LOGGING = {
        'version': 1,
        'asyncio': {
            'level': 'WARNING',
        },
        'disable_existing_loggers': False,
        'formatters': {
                'verbose': {
                       'format': '%(levelname)-8s %(asctime)s %(process)d %(thread)d %(module)s %(message)s',
                },
        },
        'handlers': {
                'log_file': {
                        'level': 'ERROR',
                        'class': 'logging.FileHandler',
                        'filename': '/home/logavanan-a/Desktop/Django/C3/c3_mis_dev/C3_WEB/static/debug.log',
                        'formatter': 'verbose'
                },
        },
        'loggers': {
                '': {
                        'handlers': ['log_file'],
                        'level': 'ERROR',
                        'propagate': True,
                },
        }
}

