# Generated by Django 3.2.4 on 2022-07-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awc',
            name='code',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
