# Generated by Django 3.2.4 on 2022-07-08 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application_masters', '0003_auto_20220707_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescent',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='awc',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='block',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='district',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='fossilahsession',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='fossilahsessioncategory',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='fossildlsessioncategory',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='fossildlsessionconfig',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='gramapanchayat',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='school',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='state',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='village',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.CreateModel(
            name='CC_AWC_DL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('deactivated_date', models.DateField()),
                ('awc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.awc')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdapplication_masters_cc_awc_dl_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedapplication_masters_cc_awc_dl_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CC AWC DL',
            },
        ),
        migrations.CreateModel(
            name='CC_AWC_AH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('deactivated_date', models.DateField()),
                ('awc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.awc')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdapplication_masters_cc_awc_ah_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedapplication_masters_cc_awc_ah_related', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CC AWC AH',
            },
        ),
    ]
