# Generated by Django 3.2.4 on 2022-08-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0005_cc_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awc',
            options={'ordering': ['village'], 'verbose_name_plural': 'AWC'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['village']},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ['name']},
        ),
    ]
