# Generated by Django 3.2.4 on 2022-08-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0006_auto_20220826_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['awc']},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'ordering': ['grama_panchayat']},
        ),
    ]
