# Generated by Django 3.2.4 on 2022-09-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0010_misreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescent',
            name='code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='adolescent',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=2),
        ),
    ]
