# Generated by Django 3.2.4 on 2022-10-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0012_alter_adolescent_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescent',
            name='site',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
