# Generated by Django 3.2.4 on 2022-07-06 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('mis', '0002_auto_20220705_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ahsession',
            options={'verbose_name_plural': 'AH Session'},
        ),
        migrations.AlterModelOptions(
            name='boysahwd',
            options={'verbose_name_plural': 'Boys AHWD'},
        ),
        migrations.AlterModelOptions(
            name='dlsession',
            options={'verbose_name_plural': 'DL Session'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='girlsahwd',
            options={'verbose_name_plural': 'Girls AHWD'},
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='ashas_female',
            new_name='health_ashas_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='ashas_male',
            new_name='health_ashas_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='ashas_total',
            new_name='health_ashas_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='awws_female',
            new_name='health_bpm_bhm_pheos_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='awws_male',
            new_name='health_bpm_bhm_pheos_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='awws_total',
            new_name='health_bpm_bhm_pheos_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='block_cluster_field_corrdinators_female',
            new_name='health_district_level_officials_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='block_cluster_field_corrdinators_male',
            new_name='health_district_level_officials_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='block_cluster_field_corrdinators_total',
            new_name='health_district_level_officials_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='block_level_officials_female',
            new_name='health_medical_officers_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='block_level_officials_male',
            new_name='health_medical_officers_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='block_level_officials_total',
            new_name='health_medical_officers_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='bpm_bhm_pheos_female',
            new_name='health_peer_educator_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='bpm_bhm_pheos_male',
            new_name='health_peer_educator_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='bpm_bhm_pheos_total',
            new_name='health_peer_educator_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='chairman_zila_parishad_female',
            new_name='health_rsk_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='chairman_zila_parishad_male',
            new_name='health_rsk_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='chairman_zila_parishad_total',
            new_name='health_rsk_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='child_developement_project_officers_female',
            new_name='health_state_level_officials_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='child_developement_project_officers_male',
            new_name='health_state_level_officials_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='child_developement_project_officers_total',
            new_name='health_state_level_officials_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='editors_female',
            new_name='icds_awws_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='editors_male',
            new_name='icds_awws_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='editors_total',
            new_name='icds_awws_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='journalists_female',
            new_name='icds_child_developement_project_officers_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='journalists_male',
            new_name='icds_child_developement_project_officers_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='journalists_total',
            new_name='icds_child_developement_project_officers_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='medical_officers_female',
            new_name='icds_district_level_officials_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='medical_officers_male',
            new_name='icds_district_level_officials_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='medical_officers_total',
            new_name='icds_district_level_officials_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='mukhiya_Pramukh_female',
            new_name='icds_peer_educator_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='mukhiya_Pramukh_male',
            new_name='icds_peer_educator_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='mukhiya_Pramukh_total',
            new_name='icds_peer_educator_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='ngo_staff_corrdinators_female',
            new_name='icds_state_level_officials_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='ngo_staff_corrdinators_male',
            new_name='icds_state_level_officials_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='ngo_staff_corrdinators_total',
            new_name='icds_state_level_officials_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='rsk_female',
            new_name='icds_supervisors_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='rsk_male',
            new_name='icds_supervisors_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='rsk_total',
            new_name='icds_supervisors_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='supervisors_female',
            new_name='media_editors_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='supervisors_male',
            new_name='media_editors_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='supervisors_total',
            new_name='media_editors_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='up_mukhiya_up_Pramukh_female',
            new_name='media_journalists_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='up_mukhiya_up_Pramukh_male',
            new_name='media_journalists_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='up_mukhiya_up_Pramukh_total',
            new_name='media_journalists_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='vc_zila_parishad_female',
            new_name='others_block_cluster_field_corrdinators_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='vc_zila_parishad_total',
            new_name='others_block_cluster_field_corrdinators_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='vc_zila_parishad_male',
            new_name='others_block_cluster_field_corrdinators_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='ward_members_female',
            new_name='others_ngo_staff_corrdinators_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='ward_members_male',
            new_name='others_ngo_staff_corrdinators_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='ward_members_total',
            new_name='others_ngo_staff_corrdinators_total',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='zila_parishad_member_female',
            new_name='panchayat_block_level_officials_female',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='zila_parishad_member_male',
            new_name='panchayat_block_level_officials_male',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='zila_parishad_member_total',
            new_name='panchayat_block_level_officials_total',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_chairman_zila_parishad_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_chairman_zila_parishad_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_chairman_zila_parishad_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_district_level_officials_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_district_level_officials_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_district_level_officials_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_mukhiya_Pramukh_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_mukhiya_Pramukh_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_mukhiya_Pramukh_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_state_level_officials_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_state_level_officials_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_state_level_officials_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_up_mukhiya_up_Pramukh_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_up_mukhiya_up_Pramukh_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_up_mukhiya_up_Pramukh_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_vc_zila_parishad_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_vc_zila_parishad_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_vc_zila_parishad_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_ward_members_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_ward_members_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_ward_members_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_zila_parishad_member_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_zila_parishad_member_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='panchayat_zila_parishad_member_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DCPU_BCPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('name_of_institution', models.CharField(max_length=150)),
                ('date_of_visit', models.DateField()),
                ('name_of_lead', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('issues_discussed', models.TextField(blank=True, null=True)),
                ('girls_10_14_year', models.IntegerField(blank=True, null=True)),
                ('girls_15_19_year', models.IntegerField(blank=True, null=True)),
                ('boys_10_14_year', models.IntegerField(blank=True, null=True)),
                ('boys_15_19_year', models.IntegerField(blank=True, null=True)),
                ('champions_15_19_year', models.IntegerField(blank=True, null=True)),
                ('adult_male', models.CharField(max_length=150)),
                ('adult_female', models.CharField(max_length=150)),
                ('teachers', models.CharField(max_length=150)),
                ('pri_members', models.IntegerField(blank=True, null=True)),
                ('services_providers', models.IntegerField(blank=True, null=True)),
                ('sms_members', models.IntegerField(blank=True, null=True)),
                ('other', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_dcpu_bcpu_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_dcpu_bcpu_related', to=settings.AUTH_USER_MODEL)),
                ('sites', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
