# Generated by Django 3.2.4 on 2022-07-07 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('mis', '0003_auto_20220706_0603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adolecentsreferred',
            options={'verbose_name_plural': 'Adolecents Referred'},
        ),
        migrations.AlterModelOptions(
            name='adolescentfriendlyclub',
            options={'verbose_name_plural': 'Adolescent Friendly Club'},
        ),
        migrations.AlterModelOptions(
            name='adolescentre_enrolled',
            options={'verbose_name_plural': 'Adolescent Re_enrolled'},
        ),
        migrations.AlterModelOptions(
            name='balsansadmetting',
            options={'verbose_name_plural': 'BalSansad Metting'},
        ),
        migrations.AlterModelOptions(
            name='dcpu_bcpu',
            options={'verbose_name_plural': 'DCPU/BCPU'},
        ),
        migrations.AlterModelOptions(
            name='followup_liaisionmetting',
            options={'verbose_name_plural': 'Follow up/Liaision metting'},
        ),
        migrations.AlterModelOptions(
            name='vlcpcmetting',
            options={'verbose_name_plural': 'VLCPC metting'},
        ),
        migrations.RenameField(
            model_name='adolecentsreferred',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='adolescentfriendlyclub',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='adolescentvocationaltraining',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='ahsession',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='balsansadmetting',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='boysahwd',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='champions',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='communityengagementactivities',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='dcpu_bcpu',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='dlsession',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='educatinalenrichmentsupportprovided',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='facedrelatedoperation',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='followup_liaisionmetting',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='girlsahwd',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='parentvocationaltraining',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='participatingmetting',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='sessionmonitoring',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='stakeholder',
            old_name='sites',
            new_name='site',
        ),
        migrations.RenameField(
            model_name='vlcpcmetting',
            old_name='sites',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sites',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Submitted for approval'), (3, 'Approved'), (4, 'Rejected'), (5, 'Cancelled')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.CreateModel(
            name='UserSiteMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_usersitemapping_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_usersitemapping_related', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyReportingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=2)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_monthlyreportingconfig_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_monthlyreportingconfig_related', to=settings.AUTH_USER_MODEL)),
                ('reporting_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reporting_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
