# Generated by Django 3.2.4 on 2022-07-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0005_auto_20220707_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adolescentre_enrolled',
            old_name='sites',
            new_name='site',
        ),
    ]
