# Generated by Django 3.2.4 on 2022-07-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0006_rename_sites_adolescentre_enrolled_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterField(
            model_name='adolecentsreferred',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='adolescentfriendlyclub',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='adolescentre_enrolled',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='adolescentvocationaltraining',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='ahsession',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='balsansadmetting',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='boysahwd',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='champions',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='communityengagementactivities',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='dcpu_bcpu',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='dlsession',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='educatinalenrichmentsupportprovided',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='facedrelatedoperation',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='followup_liaisionmetting',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='girlsahwd',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='monthlyreportingconfig',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='parentvocationaltraining',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='participatingmetting',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='sessionmonitoring',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='usersitemapping',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='vlcpcmetting',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1),
        ),
    ]
