# Generated by Django 3.2.4 on 2022-07-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0008_auto_20220710_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlcpcmetting',
            name='issues_discussed',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='vlcpcmetting',
            name='decision_taken',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
