# Generated by Django 3.2.4 on 2022-07-11 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0004_auto_20220708_0849'),
        ('mis', '0009_auto_20220711_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educatinalenrichmentsupportprovided',
            name='awc_name',
        ),
        migrations.RemoveField(
            model_name='educatinalenrichmentsupportprovided',
            name='no_of_adolescent_girls',
        ),
        migrations.AddField(
            model_name='educatinalenrichmentsupportprovided',
            name='adolescent_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.adolescent'),
        ),
        migrations.AlterField(
            model_name='educatinalenrichmentsupportprovided',
            name='duration_of_coaching_support',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
