# Generated by Django 3.2.4 on 2022-07-13 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0005_cc_school'),
        ('mis', '0010_auto_20220711_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityengagementactivities',
            name='school_name',
        ),
        migrations.AddField(
            model_name='communityengagementactivities',
            name='theme_topic',
            field=models.IntegerField(blank=True, choices=[(1, 'Theme'), (2, 'Topic')], null=True),
        ),
        migrations.AddField(
            model_name='communityengagementactivities',
            name='village_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.village'),
        ),
        migrations.AlterField(
            model_name='communityengagementactivities',
            name='adult_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityengagementactivities',
            name='adult_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communityengagementactivities',
            name='name_of_event_activity',
            field=models.IntegerField(blank=True, choices=[(1, 'Event'), (2, 'Activity')], null=True),
        ),
        migrations.AlterField(
            model_name='communityengagementactivities',
            name='organized_by',
            field=models.IntegerField(blank=True, choices=[(1, 'C3'), (2, 'Govt.')], null=True),
        ),
        migrations.AlterField(
            model_name='communityengagementactivities',
            name='teachers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
