# Generated by Django 3.2.4 on 2022-07-14 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0011_auto_20220713_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcpu_bcpu',
            name='adult_female',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcpu_bcpu',
            name='adult_male',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcpu_bcpu',
            name='teachers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CCReportNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('successes', models.TextField(blank=True, null=True)),
                ('challenges_faced', models.TextField(blank=True, null=True)),
                ('feasible_solution_to_scale_up', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_ccreportnotes_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_ccreportnotes_related', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
