# Generated by Django 3.2.4 on 2022-07-14 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0005_cc_school'),
        ('mis', '0012_auto_20220714_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcpu_bcpu',
            name='block_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.block'),
        ),
    ]
