# Generated by Django 3.2.4 on 2022-07-14 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0013_dcpu_bcpu_block_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatingmetting',
            name='block_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participatingmetting',
            name='cluster_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participatingmetting',
            name='districit_level_officials',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participatingmetting',
            name='no_of_others',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participatingmetting',
            name='no_of_pri',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participatingmetting',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
