# Generated by Django 3.2.4 on 2022-07-14 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0014_auto_20220714_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipatingMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('type_of_meeting', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('point_of_discussion', models.CharField(max_length=150)),
                ('districit_level_officials', models.IntegerField(blank=True, null=True)),
                ('block_level', models.IntegerField(blank=True, null=True)),
                ('cluster_level', models.IntegerField(blank=True, null=True)),
                ('no_of_pri', models.IntegerField(blank=True, null=True)),
                ('no_of_others', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_participatingmeeting_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_participatingmeeting_related', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ParticipatingMetting',
        ),
    ]
