# Generated by Django 3.2.4 on 2022-07-15 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0018_auto_20220714_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup_liaisionmetting',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup_liaisionmetting',
            name='district_block_level',
            field=models.IntegerField(blank=True, choices=[(1, 'District Level'), (2, 'Block Level')], null=True),
        ),
        migrations.AddField(
            model_name='followup_liaisionmetting',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
