# Generated by Django 3.2.4 on 2022-07-15 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0019_auto_20220715_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUP_LiaisionMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('district_block_level', models.IntegerField(blank=True, choices=[(1, 'District Level'), (2, 'Block Level')], null=True)),
                ('meeting', models.CharField(max_length=150)),
                ('department', models.CharField(max_length=150)),
                ('point_of_discussion', models.CharField(max_length=150)),
                ('outcome', models.CharField(max_length=150)),
                ('decision_taken', models.CharField(max_length=150)),
                ('remarks', models.CharField(max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_followup_liaisionmeeting_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_followup_liaisionmeeting_related', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
                ('user_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Follow up/Liaision metting',
            },
        ),
        migrations.DeleteModel(
            name='FollowUP_LiaisionMetting',
        ),
    ]
