# Generated by Django 3.2.4 on 2022-07-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0005_cc_school'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0020_auto_20220715_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalSansadMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('no_of_participants', models.IntegerField(blank=True, null=True)),
                ('issues_discussed', models.TextField(blank=True, null=True)),
                ('decision_taken', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_balsansadmeeting_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_balsansadmeeting_related', to=settings.AUTH_USER_MODEL)),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='application_masters.school')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
            ],
            options={
                'verbose_name_plural': 'BalSansad Metting',
            },
        ),
        migrations.AlterModelOptions(
            name='followup_liaisionmeeting',
            options={'verbose_name_plural': 'Follow up/Liaision meeting'},
        ),
        migrations.DeleteModel(
            name='BalSansadMetting',
        ),
    ]
