# Generated by Django 3.2.4 on 2022-07-18 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0021_auto_20220715_0915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balsansadmeeting',
            options={'verbose_name_plural': 'BalSansad Meeting'},
        ),
        migrations.AlterModelOptions(
            name='ccreportnotes',
            options={'verbose_name_plural': 'CC Report Notes'},
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
