# Generated by Django 3.2.4 on 2022-07-19 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mis', '0022_auto_20220718_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boysahwd',
            name='awc_name',
        ),
        migrations.RemoveField(
            model_name='girlsahwd',
            name='awc_name',
        ),
        migrations.AddField(
            model_name='boysahwd',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='boysahwd',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='girlsahwd',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='girlsahwd',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boysahwd',
            name='place_of_ahwd',
            field=models.IntegerField(blank=True, choices=[(1, 'AWC'), (2, 'School')], null=True),
        ),
        migrations.AlterField(
            model_name='girlsahwd',
            name='place_of_ahwd',
            field=models.IntegerField(blank=True, choices=[(1, 'AWC'), (2, 'School')], null=True),
        ),
    ]
