# Generated by Django 3.2.4 on 2022-07-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0025_auto_20220720_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champions',
            name='name_of_visited',
        ),
        migrations.AddField(
            model_name='champions',
            name='first_inst_visited',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], null=True),
        ),
        migrations.AddField(
            model_name='champions',
            name='seconf_inst_visited',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], null=True),
        ),
        migrations.AddField(
            model_name='champions',
            name='third_inst_visited',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], null=True),
        ),
        migrations.AlterField(
            model_name='adolescentre_enrolled',
            name='which_class_enrolled',
            field=models.IntegerField(blank=True, choices=[(1, 'Class V'), (2, 'Class VI'), (3, 'Class VII'), (4, 'Class VIII'), (5, 'Class IX'), (6, 'Class X'), (7, 'Class XI'), (8, 'Class XII')], null=True),
        ),
    ]
