# Generated by Django 3.2.4 on 2022-07-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0026_auto_20220723_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champions',
            old_name='seconf_inst_visited',
            new_name='second_inst_visited',
        ),
    ]
