# Generated by Django 3.2.4 on 2022-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0028_auto_20220825_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dlsession',
            name='session_day',
            field=models.IntegerField(blank=True, choices=[(1, 'Day-1'), (2, 'Day-2'), (3, 'Day-3'), (4, 'Day-4'), (5, 'Day-5'), (6, 'Day-6'), (7, 'Day-7'), (8, 'Day-8'), (9, 'Day-9')], null=True),
        ),
    ]
