# Generated by Django 3.2.4 on 2022-08-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0029_alter_dlsession_session_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescentre_enrolled',
            name='school_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
