# Generated by Django 3.2.4 on 2022-08-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0031_auto_20220827_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahsession',
            name='designation_data',
            field=models.IntegerField(blank=True, choices=[(1, 'ANM'), (2, 'Sahiya'), (3, 'Sevika'), (4, 'Peer Educator'), (5, 'Cluster Coordinator'), (6, 'Project Officer'), (7, 'SPO'), (8, 'Others')], null=True),
        ),
        migrations.AddField(
            model_name='ahsession',
            name='facilitator_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
