# Generated by Django 3.2.4 on 2022-08-29 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0032_auto_20220827_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adolescentfriendlyclub',
            name='designation',
        ),
    ]
