# Generated by Django 3.2.4 on 2022-08-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0034_adolescentfriendlyclub_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='adolescentfriendlyclub',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
