# Generated by Django 3.2.4 on 2022-08-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0037_adolescentvocationaltraining_training_providing_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adolescentvocationaltraining',
            name='training_subject',
        ),
    ]
