# Generated by Django 3.2.4 on 2022-08-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0039_auto_20220829_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adolescentvocationaltraining',
            name='training_subject',
        ),
        migrations.DeleteModel(
            name='TrainingSubject',
        ),
    ]
