# Generated by Django 3.2.4 on 2022-08-30 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0009_masterlookup'),
        ('mis', '0041_adolescentvocationaltraining_training_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityengagementactivities',
            name='theme_topic',
        ),
        migrations.AddField(
            model_name='communityengagementactivities',
            name='activity_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_name', to='application_masters.masterlookup'),
        ),
        migrations.AddField(
            model_name='communityengagementactivities',
            name='event_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_name', to='application_masters.masterlookup'),
        ),
    ]
