# Generated by Django 3.2.4 on 2022-08-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0042_auto_20220830_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adolescentvocationaltraining',
            name='placement_accepted',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Accepted'), (2, 'Not accepted')], null=True),
        ),
        migrations.AlterField(
            model_name='adolescentvocationaltraining',
            name='placement_offered',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='adolescentvocationaltraining',
            name='training_complated',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='adolescentvocationaltraining',
            name='type_of_employment',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Full time'), (2, 'Part time'), (3, 'Apprentice')], null=True),
        ),
        migrations.AlterField(
            model_name='parentvocationaltraining',
            name='placement_accepted',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Accepted'), (2, 'Not accepted')], null=True),
        ),
        migrations.AlterField(
            model_name='parentvocationaltraining',
            name='placement_offered',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='parentvocationaltraining',
            name='training_complated',
            field=models.IntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='parentvocationaltraining',
            name='type_of_employment',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Full time'), (2, 'Part time'), (3, 'Apprentice')], null=True),
        ),
    ]
