# Generated by Django 3.2.4 on 2022-09-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0043_auto_20220831_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlsession',
            name='session_name',
            field=models.IntegerField(blank=True, choices=[(1, 'Theroy'), (2, 'Practical')], null=True),
        ),
    ]
