# Generated by Django 3.2.4 on 2022-09-01 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0044_dlsession_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='champions',
            name='date_of_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
