# Generated by Django 3.2.4 on 2022-09-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0045_champions_date_of_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ahsession',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ahsession',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AddField(
            model_name='dlsession',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dlsession',
            name='designation_data',
            field=models.IntegerField(blank=True, choices=[(1, 'ANM'), (2, 'Sahiya'), (3, 'Sevika'), (4, 'Peer Educator'), (5, 'Cluster Coordinator'), (6, 'Project Officer'), (7, 'SPO'), (8, 'Others')], null=True),
        ),
        migrations.AddField(
            model_name='dlsession',
            name='facilitator_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dlsession',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
    ]
