# Generated by Django 3.2.4 on 2022-09-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0047_followup_liaisionmeeting_meeting_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boysahwd',
            name='hwc_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='girlsahwd',
            name='hwc_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='boysahwd',
            name='place_of_ahwd',
            field=models.IntegerField(blank=True, choices=[(1, 'AWC'), (2, 'School'), (3, 'HWC')], null=True),
        ),
        migrations.AlterField(
            model_name='girlsahwd',
            name='place_of_ahwd',
            field=models.IntegerField(blank=True, choices=[(1, 'AWC'), (2, 'School'), (3, 'HWC')], null=True),
        ),
    ]
