# Generated by Django 3.2.4 on 2022-09-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0048_auto_20220903_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmonitoring',
            name='name_of_visited',
            field=models.IntegerField(blank=True, choices=[(1, 'Village'), (2, 'AWC'), (3, 'School'), (4, 'Vocational Training Institute'), (5, 'Others')], null=True),
        ),
    ]
