# Generated by Django 3.2.4 on 2022-09-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0049_alter_sessionmonitoring_name_of_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmonitoring',
            name='name_of_place_visited',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
