# Generated by Django 3.2.4 on 2022-09-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mis', '0050_sessionmonitoring_name_of_place_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmonitoring',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='sessionmonitoring',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
