# Generated by Django 3.2.4 on 2022-09-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mis', '0051_auto_20220903_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='name_of_place_visited',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name_of_visited',
            field=models.IntegerField(blank=True, choices=[(1, 'Village'), (2, 'AWC'), (3, 'School'), (4, 'HSC'), (5, 'AWC'), (6, 'HWC'), (7, 'AFHC'), (8, 'CHC'), (9, 'PHC'), (10, 'Vocational Training Institute'), (11, 'Other Public Service Institutions'), (12, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
