# Generated by Django 3.2.4 on 2022-09-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0053_auto_20220905_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatingmeeting',
            name='department',
            field=models.IntegerField(blank=True, choices=[(1, 'Health'), (2, 'WCD'), (3, 'PRI'), (4, 'District administration'), (5, 'Block administration'), (6, 'Child protection'), (7, 'Education'), (8, 'Partner organization’s meeting'), (9, 'Others')], null=True),
        ),
        migrations.AddField(
            model_name='participatingmeeting',
            name='type_of_meeting',
            field=models.IntegerField(blank=True, choices=[(1, 'Monthly Review meeting'), (2, 'Quarterly review meeting'), (3, 'Event planning meeting'), (4, 'Issue based meeting'), (5, 'SMC meeting'), (6, 'Convergence meeting'), (7, 'Others')], null=True),
        ),
    ]
