# Generated by Django 3.2.4 on 2022-09-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0054_auto_20220905_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='name_of_visited',
            field=models.IntegerField(blank=True, choices=[(1, 'Village'), (2, 'AWC'), (3, 'School'), (4, 'HSC'), (5, 'HWC'), (6, 'AFHC'), (7, 'CHC'), (8, 'PHC'), (9, 'Vocational Training Institute'), (10, 'Other Public Service Institutions'), (11, 'Others')], null=True),
        ),
    ]
