# Generated by Django 3.2.4 on 2022-09-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0056_auto_20220905_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='participatingmeeting',
            name='district_block_level',
            field=models.IntegerField(blank=True, choices=[(1, 'District Level'), (2, 'Block Level')], null=True),
        ),
    ]
