# Generated by Django 3.2.4 on 2022-09-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0063_auto_20220921_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsection4a',
            name='participated_15_19_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
