# Generated by Django 3.2.4 on 2022-09-21 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0065_reportsection4b'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSection5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('name_of_block', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_panchayat', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_village', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_awc_code', models.CharField(blank=True, max_length=250, null=True)),
                ('girls_referred_10_14_year', models.IntegerField(blank=True, null=True)),
                ('girls_referred_15_19_year', models.IntegerField(blank=True, null=True)),
                ('boys_referred_10_14_year', models.IntegerField(blank=True, null=True)),
                ('boys_referred_15_19_year', models.IntegerField(blank=True, null=True)),
                ('girls_hwc_referred', models.IntegerField(blank=True, null=True)),
                ('girls_hwc_visited', models.IntegerField(blank=True, null=True)),
                ('girls_afhc_referred', models.IntegerField(blank=True, null=True)),
                ('girls_afhc_visited', models.IntegerField(blank=True, null=True)),
                ('girls_dh_referred', models.IntegerField(blank=True, null=True)),
                ('girls_dh_visited', models.IntegerField(blank=True, null=True)),
                ('boys_hwc_referred', models.IntegerField(blank=True, null=True)),
                ('boys_hwc_visited', models.IntegerField(blank=True, null=True)),
                ('boys_afhc_referred', models.IntegerField(blank=True, null=True)),
                ('boys_afhc_visited', models.IntegerField(blank=True, null=True)),
                ('boys_dh_referred', models.IntegerField(blank=True, null=True)),
                ('boys_dh_visited', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_reportsection5_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_reportsection5_related', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
            ],
            options={
                'verbose_name_plural': 'Report Section5',
            },
        ),
    ]
