# Generated by Django 3.2.4 on 2022-09-21 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mis', '0066_reportsection5'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSection9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('name_of_block', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_panchayat', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_village', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_awc_code', models.CharField(blank=True, max_length=250, null=True)),
                ('girls_10_14_year', models.IntegerField(blank=True, null=True)),
                ('girls_15_19_year', models.IntegerField(blank=True, null=True)),
                ('boys_10_14_year', models.IntegerField(blank=True, null=True)),
                ('boys_15_19_year', models.IntegerField(blank=True, null=True)),
                ('first_inst_visited', models.IntegerField(blank=True, null=True)),
                ('second_inst_visited', models.IntegerField(blank=True, null=True)),
                ('third_inst_visited', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_reportsection9_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_reportsection9_related', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
            ],
            options={
                'verbose_name_plural': 'Report Section9',
            },
        ),
        migrations.CreateModel(
            name='ReportSection8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('name_of_block', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_panchayat', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_village', models.CharField(blank=True, max_length=250, null=True)),
                ('event_name', models.CharField(blank=True, max_length=250, null=True)),
                ('activity_name', models.CharField(blank=True, max_length=250, null=True)),
                ('organized_by', models.CharField(blank=True, max_length=250, null=True)),
                ('girls_10_14_year', models.IntegerField(blank=True, null=True)),
                ('girls_15_19_year', models.IntegerField(blank=True, null=True)),
                ('boys_10_14_year', models.IntegerField(blank=True, null=True)),
                ('boys_15_19_year', models.IntegerField(blank=True, null=True)),
                ('champions_15_19_year', models.IntegerField(blank=True, null=True)),
                ('adult_male', models.IntegerField(blank=True, null=True)),
                ('adult_female', models.IntegerField(blank=True, null=True)),
                ('teachers', models.IntegerField(blank=True, null=True)),
                ('pri_members', models.IntegerField(blank=True, null=True)),
                ('services_providers', models.IntegerField(blank=True, null=True)),
                ('sms_members', models.IntegerField(blank=True, null=True)),
                ('other', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_reportsection8_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_reportsection8_related', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
            ],
            options={
                'verbose_name_plural': 'Report Section8',
            },
        ),
        migrations.CreateModel(
            name='ReportSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('name_of_cc', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_block', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_panchayat', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_village', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_awc_code', models.CharField(blank=True, max_length=250, null=True)),
                ('session_name', models.CharField(blank=True, max_length=250, null=True)),
                ('girls_10_14_year', models.IntegerField(blank=True, null=True)),
                ('girls_15_19_year', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_reportsection2_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_reportsection2_related', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
            ],
            options={
                'verbose_name_plural': 'Report Section2',
            },
        ),
        migrations.CreateModel(
            name='ReportSection10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('name_of_block', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_panchayat', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_village', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_awc_code', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_adolescent', models.CharField(blank=True, max_length=250, null=True)),
                ('gender', models.CharField(blank=True, max_length=250, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('parent_guardian_name', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_school', models.CharField(blank=True, max_length=250, null=True)),
                ('class_enrolled', models.CharField(blank=True, max_length=250, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_reportsection10_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_reportsection10_related', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
            ],
            options={
                'verbose_name_plural': 'Report Section10',
            },
        ),
    ]
