# Generated by Django 3.2.4 on 2022-09-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0068_reportsection6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educatinalenrichmentsupportprovided',
            name='standard',
            field=models.PositiveIntegerField(choices=[(1, 'VIII'), (2, 'IX'), (3, 'X')], verbose_name='Class'),
        ),
    ]
