# Generated by Django 3.2.4 on 2022-09-23 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application_masters', '0012_alter_adolescent_gender'),
        ('mis', '0069_alter_educatinalenrichmentsupportprovided_standard'),
    ]

    operations = [
        migrations.AddField(
            model_name='balsansadmeeting',
            name='issues_discussion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues_discussion', to='application_masters.masterlookup'),
        ),
    ]
