# Generated by Django 3.2.4 on 2022-09-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0070_balsansadmeeting_issues_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportsection4b',
            name='tt_shot_10_14_year',
        ),
        migrations.RemoveField(
            model_name='reportsection4b',
            name='tt_shot_15_19_year',
        ),
    ]
