# Generated by Django 3.2.4 on 2022-09-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0071_auto_20220924_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsection10',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsection7',
            name='school_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsection8',
            name='village_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsection9',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
