# Generated by Django 3.2.4 on 2022-09-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0072_auto_20220926_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsection3',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsection4a',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsection4b',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsection5',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsection6',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
