# Generated by Django 3.2.4 on 2022-09-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0075_historyrecord_end_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyrecord',
            name='execution_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
