# Generated by Django 3.2.4 on 2022-09-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0076_alter_historyrecord_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsection9',
            name='first_inst_visited',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reportsection9',
            name='second_inst_visited',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='reportsection9',
            name='third_inst_visited',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
