# Generated by Django 3.2.4 on 2022-09-28 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('mis', '0077_auto_20220928_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='UntrustVLCPCMetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('unique_id', models.IntegerField(blank=True, null=True)),
                ('name_of_block', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_panchayat', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_village', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_awc_code', models.CharField(blank=True, max_length=250, null=True)),
                ('date_of_meeting', models.CharField(blank=True, max_length=250, null=True)),
                ('no_of_participants_planned', models.IntegerField(blank=True, null=True)),
                ('no_of_participants_attended', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_untrustvlcpcmetting_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_untrustvlcpcmetting_related', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
            ],
            options={
                'verbose_name_plural': 'Untrust VLCPC Metting',
            },
        ),
        migrations.CreateModel(
            name='UntrustEducatinalEnrichmentSupportProvided',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('unique_id', models.IntegerField(blank=True, null=True)),
                ('name_of_block', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_panchayat', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_village', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_awc_code', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_adolescent', models.CharField(blank=True, max_length=250, null=True)),
                ('parent_guardian_name', models.CharField(blank=True, max_length=250, null=True)),
                ('enrolment_date', models.CharField(blank=True, max_length=250, null=True)),
                ('standard', models.CharField(blank=True, max_length=250, null=True)),
                ('duration_of_coaching_support', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_untrusteducatinalenrichmentsupportprovided_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_untrusteducatinalenrichmentsupportprovided_related', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
            ],
            options={
                'verbose_name_plural': 'Untrust Educatinal Enrichment SupportProvided',
            },
        ),
        migrations.CreateModel(
            name='UntrustDCPU_BCPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Active'), (2, 'Inactive')], db_index=True, default=1)),
                ('server_created_on', models.DateTimeField(auto_now_add=True)),
                ('server_modified_on', models.DateTimeField(auto_now=True)),
                ('unique_id', models.IntegerField(blank=True, null=True)),
                ('name_of_block', models.CharField(blank=True, max_length=250, null=True)),
                ('name_of_institution', models.CharField(max_length=150)),
                ('date_of_visit', models.CharField(max_length=150)),
                ('name_of_lead', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('issues_discussed', models.TextField(blank=True, null=True)),
                ('girls_10_14_year', models.IntegerField(blank=True, null=True)),
                ('girls_15_19_year', models.IntegerField(blank=True, null=True)),
                ('boys_10_14_year', models.IntegerField(blank=True, null=True)),
                ('boys_15_19_year', models.IntegerField(blank=True, null=True)),
                ('champions_15_19_year', models.IntegerField(blank=True, null=True)),
                ('adult_male', models.IntegerField(blank=True, null=True)),
                ('adult_female', models.IntegerField(blank=True, null=True)),
                ('teachers', models.IntegerField(blank=True, null=True)),
                ('pri_members', models.IntegerField(blank=True, null=True)),
                ('services_providers', models.IntegerField(blank=True, null=True)),
                ('sms_members', models.IntegerField(blank=True, null=True)),
                ('other', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdmis_untrustdcpu_bcpu_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modifiedmis_untrustdcpu_bcpu_related', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sites.site')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mis.task')),
            ],
            options={
                'verbose_name_plural': 'Untrust VLCPC Metting',
            },
        ),
    ]
