# Generated by Django 3.2.4 on 2022-09-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0079_auto_20220929_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='untrustdcpu_bcpu',
            name='date_of_visit1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
