# Generated by Django 3.2.4 on 2022-09-30 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0080_untrustdcpu_bcpu_date_of_visit1'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsection1',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportsection2',
            name='unique_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
