# Generated by Django 3.2.4 on 2022-10-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0082_champions_fourth_inst_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportsection9',
            name='fourth_inst_visited',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
