# Generated by Django 3.2.4 on 2022-10-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0083_reportsection9_fourth_inst_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup_liaisionmeeting',
            name='departments',
            field=models.IntegerField(blank=True, choices=[(1, 'Health'), (2, 'WCD'), (3, 'PRI'), (4, 'District administration'), (5, 'Block administration'), (6, 'Child protection'), (7, 'Education'), (8, 'Partner organization’s meeting'), (9, 'Others')], null=True),
        ),
        migrations.AlterField(
            model_name='followup_liaisionmeeting',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
