# Generated by Django 3.2.4 on 2022-11-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0086_auto_20221018_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balsansadmeeting',
            name='issues_discussed',
        ),
        migrations.AlterField(
            model_name='adolescentvocationaltraining',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
