# Generated by Django 3.2.6 on 2022-11-29 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mis', '0088_auto_20221102_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ahsession',
            name='session_days',
        ),
        migrations.RemoveField(
            model_name='dlsession',
            name='session_days',
        ),
    ]
